# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a0b165b14413ce1f8745eca9c2ddcff1e9fe331c95a80efa039451746abca7a770a04983f4055fac434e6333b4d16f92790e6fd82e15bd25186f320446411db

test:
  secret_key_base: 71755627c02c43d95721587b22ced302fc96753e58bffe2892ca7940e2cf520cc3e70a53c219f1e281fe6884d779a8fddb2a37da4f65a3d61dd5aefade070f56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
